# Day 1: Python Basics & NumPy

**Welcome!** 
The objectives of today are as follows:
- remind you about the basics - typical data structures such as lists, dictionaries, arrays
- remind you about structure of custom-made functions
- make you less scared of error messages
- prepare you to work with multi-dimensional arrays - a staple for the next days


**How will we go about it?**
Today has two parts:

1. A short **demo** (this notebook, top half) — we'll go through it together.
2. A set of **tiered exercises** (bottom half) — you work through these at your own pace.

The exercises are organised into four tiers:

| Tier | What it means |
|---|---|
| **Tier 1 - Core** | Directly mirrors what we just did in the demo. Aim to complete these. |
| **Tier 2 - Applications** | Combines a few ideas together, closer to a real workflow. |
| **Tier 3 - Extension** | Open-ended, may require you to look things up. Optional — a bonus if you have time. |

**Nobody is expected to finish everything.** Work at your own pace, and flag us down if you get stuck.


---
## Demo — Part A: Python Basics Refresher

A fast pass to confirm we're all on the same page before moving to NumPy. If any of this is
unfamiliar, flag it now rather than later!


### Variables and core types

In [5]:
# Core types: int, float, str, bool
station_name = "Antananarivo"

#Note - this is different than the above
station_name = "Antananarivo"

station_id = 260
elevation_m = 1540.5
is_automatic = False

station_id="260"

print(station_name, station_id, elevation_m, is_automatic)
print(type(station_name), type(station_id), type(elevation_m), type(is_automatic))


Antananarivo 260 1540.5 False
<class 'str'> <class 'str'> <class 'float'> <class 'bool'>


### Lists and dictionaries

In [28]:
# A list: an ordered sequence of values
daily_temps = [12.5, 15.0, 9.8, 22.3, 18.1, 23.5, 27.3]
print("\nlist")
print(daily_temps)

# working with a list - selecting, slicing - note the Pythonic indexing - i.e. the first element has index==0
print(daily_temps[0])     # first element
print(daily_temps[-1])     # last element
print(daily_temps[1:3])    # slice
print(len(daily_temps))


list
[12.5, 15.0, 9.8, 22.3, 18.1, 23.5, 27.3]
12.5
27.3
[15.0, 9.8]
7


In [8]:
# A dictionary: a set of labeled values
station_info = {"name": "Bole Airport", "id": 260, "elevation_m": 1535.0}

print("\ndictionary")

print(station_info)

#selecting a particular element
print(station_info["name"])

print(station_info["elevation_m"])


#listing keys
print(station_info.keys())


dictionary
{'name': 'Bole Airport', 'id': 260, 'elevation_m': 1535.0}
Bole Airport
1535.0
dict_keys(['name', 'id', 'elevation_m'])


In [17]:
stations={"Tana":{"name": "Antananrivo Airport", "latitude": -34.5, "elevation_m": 1535.0},
         "Toaliara": {"name": "Toaliars", "latitude": -30.5, "elevation_m": 5.0}}

In [18]:
stations["Tana"]["name"], stations["Tana"]["latitude"]


('Antananrivo Airport', -34.5)

### Iterating through lists

In [21]:
#iterating through elements of list:
#ordinary iterator
print("iterating")
for x in daily_temps:
    print(x)
print("end")

iterating
12.5
15.0
9.8
22.3
18.1
23.5
27.3
end


In [27]:
#enumerator - gives an index together with value
print("\nenumerating")
for i,x in enumerate(daily_temps):
    print(i,x)


enumerating
0 12.5
1 15.0
2 9.8
3 22.3
4 18.1
5 23.5
6 27.3


### Iterating through dictionaries

In [31]:
#iterating through a dictionary:

#ordinary iterator - this gives only keys
print("\niterating")
for x in station_info:
    print(x)


iterating
name
id
elevation_m


In [ ]:
#enumerator - index and key, but no value
print("\nenumerating")

for i,x in enumerate(station_info):
    print(i,x)

In [37]:
print("\niterating through items - proper iteration through array")
for key,x in station_info.items():
    print(key,x)


iterating through items - proper iteration through array
name Bole Airport
id 260
elevation_m 1535.0


### Loops vs. list comprehensions vs. NumPy

Same task, let's try to convert a bunch of measurements in deg C to deg F
three ways. Watch how the *style* changes even though two of these are doing
exactly the same thing under the hood.


In [38]:
#preparing some data
# let's try to convert deg C to deg F
daily_temps = [12.5, 15.0, 9.8, 22.3, 18.1,23.5,27.3]  # a "week" of daily temps in deg Celsius

# Version 1: explicit loop

temps_f_loop = []
for t in daily_temps:
    temps_f_loop.append(t * 9/5 + 32)

print("loop:", temps_f_loop)


loop: [54.5, 59.0, 49.64, 72.14, 64.58, 74.3, 81.14]


In [40]:
# version 2: list comprehension
# Same result, more compact. IMPORTANT: this is still iterating under the hood —
# it is NOT faster than the loop above, just terser to write.
temps_f_comp = [t * 9/5 + 32 for t in daily_temps]

print("comprehension:", temps_f_comp)


comprehension: [54.5, 59.0, 49.64, 72.14, 64.58, 74.3, 81.14]


In [41]:
# Version 3: NumPy, vectorized
import numpy as np

#we convert our list to a numpy array
daily_temps_arr = np.array(daily_temps)

#now we do not have to interate through elements - we can apply calculation to the entire array at one go
temps_f_vec = daily_temps_arr * 9/5 + 32

print("vectorized:   ", temps_f_vec)

# Confirm all three approaches agree
print(temps_f_loop==temps_f_comp)
print(temps_f_loop==list(temps_f_vec))


vectorized:    [54.5  59.   49.64 72.14 64.58 74.3  81.14]
True
True


Try running the conversion formula directly on the **plain list** (skipping the loop/comprehension).
What happens? Why?


In [42]:
# what error do you get, and why?
daily_temps * 9/5 + 32


TypeError: unsupported operand type(s) for /: 'list' and 'int'

### Timing the three approaches

At small scale the difference is invisible. Let's try it on a year of hourly data
(~8,760 values) and see what happens.


In [44]:
# let's prepare some data
np.random.seed(0)
year_hourly_c = np.random.normal(loc=12, scale=6, size=8760)   # made up hourly temps, deg C
year_hourly_list = list(year_hourly_c)
year_hourly_list

[np.float64(22.584314075805985),
 np.float64(14.40094325020334),
 np.float64(17.872427904634435),
 np.float64(25.445359195208745),
 np.float64(23.205347940899806),
 np.float64(6.1363327207415335),
 np.float64(17.700530505153537),
 np.float64(11.091856750213813),
 np.float64(11.380686889238653),
 np.float64(14.463591011630234),
 np.float64(12.864261426965268),
 np.float64(20.72564104177785),
 np.float64(16.566226350881962),
 np.float64(12.730050098956971),
 np.float64(14.663179396472554),
 np.float64(14.002045964245601),
 np.float64(20.964474438945636),
 np.float64(10.769050417405195),
 np.float64(13.878406209905409),
 np.float64(6.875425564189651),
 np.float64(-3.317938895004472),
 np.float64(15.921711572642163),
 np.float64(17.186617193157034),
 np.float64(7.547009877561348),
 np.float64(25.618527743925647),
 np.float64(3.273805952407411),
 np.float64(12.274551103808676),
 np.float64(10.876896899844999),
 np.float64(21.196675286150743),
 np.float64(20.81615261940171),
 np.float64(12.9

In [45]:
%%timeit -n1000
#checking time with loop - we will use %timeit decorator, but it needs to be a oneliner, so we create a function that executes the loop
result = []
for t in year_hourly_list:
    result.append(t * 9/5 + 32)

823 μs ± 9.58 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [46]:
print("List comprehension:")
%timeit -n1000 result=[t * 9/5 + 32 for t in year_hourly_list]

List comprehension:
846 μs ± 3.44 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [47]:
print("NumPy vectorized:")
%timeit -n1000 year_hourly_c * 9/5 + 32


NumPy vectorized:
9.99 μs ± 3.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


**Takeaway:** the loop and the comprehension come out roughly similar — comprehensions are a
*style* improvement, not a *performance* one. The vectorized NumPy version wins by a wide margin
because there's no explicit Python-level iteration at all — the whole array is processed at once.


### Functions

In [48]:
# we can define our own functions using the following syntax:

def celsius_to_fahrenheit(temp_c):
    """Convert a single Celsius value to Fahrenheit."""
    output=temp_c * 9/5 + 32
    return output

#example of use - converting single value
print(celsius_to_fahrenheit(20))

#example of use - in list comprehension
result=[celsius_to_fahrenheit(x) for x in daily_temps]
print(result)

#but we can also apply this particular function on the array of data
result=celsius_to_fahrenheit(daily_temps_arr)
print(result)

68.0
[54.5, 59.0, 49.64, 72.14, 64.58, 74.3, 81.14]
[54.5  59.   49.64 72.14 64.58 74.3  81.14]


In [50]:
#functions can have several arguments, including default ones that do not need to be passed
def is_above_threshold(temp, threshold=25):
    """Return True if temp exceeds threshold (default 25)."""
    return temp > threshold

# see different ways of invoking the function defined above
print(is_above_threshold(30))
print(is_above_threshold(20))
print(is_above_threshold(20, threshold=15))
print(is_above_threshold(20, 15))


True
False
True
True


### A quick word on error messages

You *will* see errors this week — that's normal, not a sign you've broken something.
Python's tracebacks look intimidating but usually tell you exactly what went wrong and where.
Read from the **bottom up**: the last line is usually the actual error message.


In [51]:
# Run this on purpose and read the traceback from the bottom up
daily_temps = [12.5, 15.0, 9.8, 22.3, 18.1]
print(daily_temps[10])


IndexError: list index out of range

---
## Demo — Part B: NumPy

This is the main event of the day — the concepts here (especially **broadcasting** and
**axis-based reductions**) are the foundation for everything we do with xarray later in the week.


### Creating arrays

In [52]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)          # start, stop, step
c = np.linspace(0, 1, 5)         # start, stop, N evenly spaced points
zeros = np.zeros(5)
ones = np.ones((2, 3))           # 2 rows, 3 columns
#creating array filled with nans is more complex
nans=np.zeros((2,3))
nans[:]=np.nan

print(a)
print(b)
print(c)
print(zeros)
print(ones)
print(nans)

[1 2 3 4 5]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[nan nan nan]
 [nan nan nan]]


### Missing data: `np.nan`

Missing values are a constant fact of life in observational climate data. NumPy represents
a missing float as `np.nan` ("Not a Number").


In [ ]:
temps_with_gap = np.array([12.5, 15.0, np.nan, 22.3, 18.1])

print(temps_with_gap)

#checking for nans
isnan=np.isnan(temps_with_gap) # boolean array flagging NaNs
print("nans",isnan)

#checking for valid data
isvalid=~np.isnan(temps_with_gap) # boolean array flagging NaNs, but then - inverting the boolean array
print("valid:",isvalid)

#calculating with nans

result=temps_with_gap*9/5+32
print(result) #still nan

#watch out for this
print(np.mean(temps_with_gap))           # careful — this propagates to NaN!
print(np.nanmean(temps_with_gap))        # this ignores NaNs

### Shape, dtype, and reshaping

In [54]:
#prepare some data
station_temps = np.array([
    [12.5, 15.0, 9.8, 22.3, 18.1, 12.5, 17.1],   # station A, 7 days
    [11.2, 14.8, 10.1, 21.9, 17.5, 17.9, 17.9],  # station B, 7 days
    [13.0, 15.6, 9.2, 22.8, 18.6, 19.0, 21.1],   # station C, 7 days
])

#checking shape and data type
print(station_temps.shape)   # (stations, days)
print(station_temps.dtype)

#flattening to 1D
flat = station_temps.reshape(-1)   # flatten to 1D
print(flat.shape) #one dimensional array

#reshaping back to 2D
daily_temps=flat.reshape(-1,1)
print(daily_temps.shape) #two dimensional array


(3, 7)
float64
(21,)
(21, 1)


### Indexing, slicing, and boolean masking
Boolean masking is probably the single most-used NumPy skill in climate data work — worth spending real time getting comfortable with this.


In [65]:
daily_temps = np.array([12.5, 15.0, 9.8, 22.3, 18.1, 12.5, 17.1])

print(daily_temps[2])          # single element
print(daily_temps[1:4])        # slice

#inverting the sequence of the array:
daily_temps[::-1]

#masking
hot_mask = daily_temps > 20
print(hot_mask)                # boolean array

print(daily_temps[hot_mask])   # only the values where mask is True

# often written in one line:
print(daily_temps[daily_temps > 20])

warm_mask = (daily_temps <15) & (daily_temps >10)
print(warm_mask)                # boolean array

print(daily_temps[warm_mask])   # only the values where mask is True


9.8
[15.   9.8 22.3]
[False False False  True False False False]
[22.3]
[22.3]
[ True False False False False  True False]
[12.5 12.5]


In [63]:
daily_temps > 20

array([False, False, False,  True, False, False, False])

### Vectorized arithmetic

In [67]:
daily_temps = np.array([12.5, 15.0, 9.8, 22.3, 18.1, 12.5, 17.1])

print(daily_temps.mean())
print(daily_temps.std())
daily_temps.min()

15.328571428571426
3.8931127045864273


np.float64(9.8)

### "where" functions

In [ ]:
#this function has two functions

print(np.where(daily_temps > 15))   # this will give us indices of values meeting the condition
print(np.where(daily_temps > 15, "warm", "cool"))   # elementwise conditional, no loop needed


### Calculations on arrays
This is relatively straightforward if arrays have identical shapes

In [ ]:
#preparing some data

# station_temps: shape (3 stations, 5 days)
station_min_temps = np.array([
    [12.5, 15.0, 9.8, 22.3, 18.1],
    [11.2, 14.8, 10.1, 21.9, 17.5],
    [13.0, 15.6, 9.2, 22.8, 18.6],
])

station_max_temps = np.array([
    [15.4, 18.0, 13.7, 25.5, 21.0],
    [14.7, 17.2, 13.4, 25.3, 20.5],
    [16.1, 18.5, 12.3, 25.4, 21.3],
])

# calcualating mean temperature
station_mean_temps = (station_min_temps+station_max_temps)/2

print(station_mean_temps)

### Broadcasting

Broadcasting lets NumPy apply an operation between arrays of *different but compatible* shapes,
without writing an explicit loop. This is the concept that is a bit tricky.


In [ ]:
#preparing some data

# station_temps: shape (3 stations, 5 days)
station_temps = np.array([
    [12.5, 15.0, 9.8, 22.3, 18.1],
    [11.2, 14.8, 10.1, 21.9, 17.5],
    [13.0, 15.6, 9.2, 22.8, 18.6],
])

# a calibration offset per station: shape (3,)
station_offset = np.array([0.5, -0.2, 0.1])

# To apply a per-station offset correctly, we need the offset to align with the
# STATIONS axis, not the days axis. We do this by reshaping it to (3, 1):
station_offset_col = station_offset.reshape(-1, 1)
print(station_temps.shape)
print(station_offset_col.shape)

corrected = station_temps + station_offset_col
print(corrected)



In [ ]:
# Broadcasting lines up the LAST axis. Here that means the offset (3,) does NOT
# line up with the days axis (5,) — this will raise an error. Try it:
print(station_temps.shape)
print(station_offset.shape)
station_temps + station_offset



**Broadcasting rule of thumb:** NumPy compares shapes from the right. Dimensions are compatible
if they're equal, or if one of them is 1. `(3, 5)` and `(3, 1)` are compatible (the `1` gets
"stretched" to match `5`); `(3, 5)` and `(3,)` are NOT compatible, because `(3,)` is compared
against the trailing `5`, not the leading `3`.


### Array reshaping

In [ ]:
#preparing some data - daily temperature data for three weeks
daily_temps = np.array([12.5, 15.0, 9.8, 22.3, 18.1, 12.5, 17.1, 11.2, 14.8, 10.1, 21.9, 17.5, 17.9, 17.9, 13.0, 15.6, 9.2, 22.8, 18.6, 19.0, 21.1]
)

print(daily_temps.shape)

#now let's reshape
temps_by_week=daily_temps.reshape((3,7))
print(temps_by_week.shape)

#let's see if reshaping went well
print(daily_temps[0:7])
print(temps_by_week[0])

#this is when reshaping goes badly
temps_by_week_bad=daily_temps.reshape((7,3))
print(temps_by_week_bad.shape)

print(daily_temps[0:7])
print(temps_by_week_bad[:,0])


**Reshaping rule of thumb:** NumPy reshapes arrays from the right. So with the reshaping as above - it will take the first 7 values from the source array and put them into first row, etc. till it creates 3 rows.

### Array subsetting

In [ ]:
# let's work with our "by week" data
print(temps_by_week.shape)

#select first week
first_week=temps_by_week[0,:]
print(first_week.shape)

#select first weeks, but slightly different way
first_week=temps_by_week[0:1,:]
print(first_week.shape)

#select first two weeks
first_two_weeks=temps_by_week[0:2,:]
print(first_two_weeks.shape)


### Axis-based reductions

In [69]:
#creating some data
# 4 stations - in rows, 6 days each - in columns
station_temps = np.array([
    [12.5, 15.0, 9.8, 22.3, 18.1,19.5],
    [11.2, 14.8, 10.1, 21.9, 17.5,19.6],
    [13.0, 15.6, 9.2, 22.8, 18.6,20.0],
    [13.2, 15.8, 9.8, 22.9, 18.3,20.5],
])

#over the entire array
print(station_temps.mean())

# shape: (stations, days)
print(station_temps.shape)

# we can calculate average along array axis:
print("Mean per station (average over days):", station_temps.mean(axis=1))
print("Mean per day (average over stations):", station_temps.mean(axis=0))


16.333333333333332
(4, 6)
Mean per station (average over days): [16.2        15.85       16.53333333 16.75      ]
Mean per day (average over stations): [12.475 15.3    9.725 22.475 18.125 19.9  ]


**Collapsing rule:** `axis=0` collapses the *first* (or *zeroth*) dimension (stations), leaving one value per the second dimension (day).
`axis=1` collapses the *second* dimension (days), leaving one value per the first dimesion (station).


---
## Exercises


In [ ]:
#making sure you are using numpy library
import numpy as np

### Tier 1 - Core


In [72]:
# --- tier 1 data ---
daily_temps = np.array([12.5, 15.0, 9.8, 22.3, 18.1, 19.0, 8.4])
# 1 "week" of mean daily temperature (deg C), single station

hourly_wind_knots = np.array([2.5, 1.0, 0.8, 2.3, 1.1, 1.0, 0.4, 0.8, 0.2,0.3,0.4,0.3,1.2,1.5,2.5,2.0,2.0,2.1,2.2,2.5,1.8,2.6,2.1,2.0])
# 24 hours of mean hourly wind (knots), single station

In [83]:
# 1. Convert hourly_wind from knots to m/s three ways, and confirm all three
# 1 knot = 1852 m/h
#    give the same result:
#      (a) an explicit loop
#      (b) a list comprehension
#      (c) vectorized NumPy


In [ ]:
# 2. Create an array of 11 evenly spaced values between 0 and 100 using np.linspace.
#    Print its shape and dtype.


In [ ]:
# 3. Using boolean indexing, find hours when hourly_wind is above 1 m/s. Assume the series starts at 01:00


In [ ]:
# 4. Using slicing, split hourly_wind into daytime (7am-6pm) and nighttime (7pm-6am) data  
#    as two separate arrays. Wind data start on 01:00


In [ ]:
# 5. Reverse hourly_wind using slicing (no loop, no function -- just slicing syntax).


In [ ]:
# 6. Create a boolean mask for hours in hourly_wind that are BETWEEN 1 and 1.5 m/s (inclusive). 


In [ ]:
# 7. Back to temperature - suppose you have daily HIGH and LOW temperatures for the same week:
daily_highs = np.array([16.0, 18.5, 12.0, 25.0, 21.0, 22.6, 11.0])
daily_lows  = np.array([9.0, 11.0, 7.5, 18.0, 14.5, 15.0, 5.5])

#    Compute the daily temperature RANGE (high - low) for each day, then find
#    which day had the largest range? 
#    do you happen to know a function that does it? if not - how would you go about it using functions that we have used above?
#    readup on function argmax()


In [ ]:
# 8. Write two functions, kt_to_ms(data) and mc_to_kt(data), for converting between
#    knots and m/s. Then confirm that converting a value from kt to m/s
#    and back to kt returns the original value.



### Tier 2 - Applications

In [ ]:
# --- tier 2 data ---

# time series (week) of data for a single station
# shape: (1 station, 7 days)
daily_temps = np.array([12.5, 15.0, 9.8, 22.3, 18.1, 19.0, 8.4])

# as above, but with some data gaps
daily_temps_gappy = np.array([12.5, 15.0, 9.8, np.nan, 22.3, 18.1, 19.0, np.nan, 8.4])

# as above but for 4 stations
# shape: (4 stations, 7 days)
station_temps = np.array([
    [12.5, 15.0, 9.8, 22.3, 18.1, 19.0, 8.4],
    [11.2, 14.8, 10.1, 22.5, 17.5, 18.6, 9.0],
    [13.0, 15.6, 9.2, 22.8, 18.6, 19.4, 8.1],
    [10.8, 14.2, 10.5, 21.2, 18.0, 18.1, 9.4],
])

# as above, but with data gaps
# shape: (4 stations, 7 days)
station_temps_gappy = np.array([
    [12.5, 15.0, 9.8, 22.3, 18.1, 19.0, 8.4],
    [11.2, 14.8, 10.1, np.nan, 17.5, 18.6, 9.0],
    [13.0, 15.6, 9.2, 22.8, 18.6, 19.4, 8.1],
    [10.8, 14.2, 10.5, 21.2, np.nan, 18.1, 9.4],
])


# per-station calibration offset, 
# shape (4,)
station_offset = np.array([0.5, -0.2, 0.1, -0.4])



In [ ]:
# 1. Compute the mean temperature PER STATION (i.e. averaged over days) and
#    the mean temperature PER DAY (i.e. averaged over stations).
#    Think carefully about which axis to use for each.



In [ ]:
# 2. Apply station_offset to station_temps correctly, so that each station's
#    entire week of temperatures is shifted by its own offset.
#    Hint: you'll need to reshape station_offset first. What shape does it need to be,
#    and why?



In [ ]:
# 3. Count how many missing values are in station_temps_gappy for each station.


In [ ]:
# 4. Write a function `fraction_above(arr, threshold)` that returns the fraction
#    (0 to 1) of values in a 1D array exceeding a given threshold. Test it on
#    daily_temps and on one row of station_temps.
#    would you know how to apply this function over axes in the station_temps?
#    read up on apply_along_axis()


In [ ]:
# 5. Find which STATION had the single highest reading anywhere in station_temps,
#    and which DAY (across all stations) had the highest reading.



In [ ]:
# 6. Compute an anomaly: for each station, subtract that station's own weekly
#    mean from each of its daily values (so each station's anomalies average to
#    roughly zero). Use broadcasting -- no loop needed.



In [ ]:
# 7. Apply station_offset (from the setup cell) to station_temps, then compute
#    what FRACTION of the corrected readings exceed 17 degrees, per station.
#    (Combine broadcasting + boolean masking + axis reduction.)



### Tier 3 - Advanced


In [ ]:
# ---  tier 3 data ---

# a "toy" multi-year daily temperature record
# shape (3 years, 365 days) 
# don't worry about the details of how these data are obtained below
np.random.seed(42)
n_years, n_days = 10, 365
year_temps = np.round((
    10
    + 12 * np.sin(np.linspace(0, 2 * np.pi, n_days))   # seasonal cycle
    + np.random.normal(0, 2, size=(n_years, n_days))    # year-to-year noise
),2)

In [ ]:
# 1. Compute a simple day-of-year climatology: the mean temperature for each
#    calendar day, averaged across all 3 years. What shape is the result, and why?



In [ ]:
# 2. Using np.where, build a categorical array that labels each value in year_temps
#    as "frost" (< 0), "mild" (0-20), or "hot" (> 20) -- without writing a loop.
#    Hint: np.where can be nested.



In [ ]:
# 3. Spot the bug: the cell below computes an anomaly (departure from climatology)
#    but the broadcasting is wrong, giving a plausible-looking but INCORRECT result.
#    Find the bug, explain it in a comment, and fix it.

climatology = year_temps.mean(axis=1) 
anomaly = year_temps - climatology.reshape(-1,1) 
print(anomaly.shape,climatology.shape)


In [ ]:
# 4. Compute the day-of-year STANDARD
#    DEVIATION across years (still one value per calendar day). Then flag which
#    (year, day) values in year_temps are more than 2 standard deviations away
#    from that day's climatological mean -- a simple "extreme event" detector.


In [ ]:
# 5. Vectorize a rolling 3-day average of year_temps for a SINGLE year
#    (e.g. year_temps[0]) without writing an explicit Python loop.
#    Hint: look into np.convolve, or alternatively - building the average from three
#    overlapping slices of the array added together.


In [ ]:
# 6. Can you try to fill the missing data in the daily_temps_gappy with a mean of values from the day before and after the gap?

